on:
  workflow_dispatch:
  push:
jobs:
  run:
    name: Run the Python script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Python Script
        run: python3 script2.py
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: Image output
          # Destination path
          path: output_images2
